---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6
  - name: debian-8.1
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openfortivpn]
