---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: debian-7
  - name: debian-8
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openfortivpn]
