---
driver:
  name: docker
  binary: docker
  use_sudo: false

platforms:
  - name: debian-7
  - name: debian-8
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openfortivpn]
