AllCops:
  Include:
    - metadata.rb
    - '**/Gemfile'
    - '**/Guardfile'
    - attributes/**/*
    - definitions/**/*
    - libraries/**/*
    - providers/**/*
    - recipes/**/*
    - resources/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - cookbooks/**/*
    - vendor/**/*
    - test/integration/data_bags/*
    - test/integration/encrypted_data_bag_secret
